#!/bin/bash

################################
#   executes redis-cli command on cluster
################################

function usage() {
cat >&2 << __USAGE__

Usage: ${0} [-v] -m mode -с command [-o options]

Where:
-v             : verbose
-m mode        : mongodb mode (mongod - shard instance, mongoc - config
instance , mongos - mongo services)
-o options     : additional options to pass to mongo
-c command     : start|stop|restart
__USAGE__
}

while getopts "vh:p:u:P:m:c:" option;
do case "${option}" in

v)
    verbose="-v";;
m)
    mode="${OPTARG}";;
c)
    command="${OPTARG}";;
o)
    options="${OPTARGS}";;
*)
    usage
    exit 2;;
esac
done

if [ -z "${mode}" ] || [ -z "${command}" ]
then
    usage
    exit 1
fi

if [ "$mode" != "mongod" ] && [ "$mode" != "mongoc" ] && [ "$mode" != "mongos" ]
then
    usage
    exit 1
fi

if [ "$command" != "start" ] && [ "$command" != "stop" ] && [ "$command" != "stop" ]
then
    usage
    exit 1
fi


