#!/bin/bash

mongo=`which mongo`

#echo $mongo
db="'catalogentry'"
coll="'catalogentry'"
ev="db"

function usage() {
  cat << __USAGE__
  Usage: ${0}
__USAGE__
}

$mongo greenapi307p.stress.ch3.s.com:20000/admin -uDBMON -pch3ck1ng --eval="db=db.getSiblingDB($db);print('Collection data storage efficiency:');db.catalogentry.stats().size/db.catalogentry.stats().storageSize"

$mongo greenapi307p.stress.ch3.s.com:20000/admin -uDBMON -pch3ck1ng --eval="db=db.getSiblingDB($db);print('DB data storage efficiency:');(db.stats().dataSize + db.stats().indexSize)/ db.stats().fileSize"

